### ISSUE TITLE
Transfer ownership so I can use Dockerhub

### ISSUE THREAD

**Issue by mbucc** [naquad/shmig#19]
@naquad Do you mind transferring ownership of this repo to me?

Looks like in order to use Dockerhub, I need to owner the repo so I can setup automated builds.  I tried, and it only could see my mbucc/shmig repo.  (Which I deleted, as I only commit here now.)

I have a current project where I will use shmig on.  I want to try out docker containers for automated testing of shmig.

**Comment by mbucc** [comment]
https://help.github.com/articles/about-repository-transfers/

**Comment by naquad** [comment]
So be it. You've spent quite some time maintaining and developing this project. I've just requested transfer.

**Comment by mbucc** [comment]
@naquad Thanks!  Just let me know if you get active here again, and I can pass it back.  It's been a pleasure working with your code.
